version: "3"
services:
  sqs-lambda-run:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
      SQS_URL: "http://localhost:9324/queue/example"
      CREATE_QUEUE: "true"
      LAMBDA_HANDLER: "index.handler"
      LAMBDA_ENDPOINT: "http://localhost:9001"
